name: Build and deploy ASP.Net Core app to an Azure Web App

env:
  ASPNETCORE_ENVIRONMENT: "Production"
  AZURE_WEBAPP_NAME: wisgenix-content-app
  AZURE_WEBAPP_PACKAGE_PATH: './publish'
  DOTNET_VERSION: '9.x'
  SOLUTION_PATH: "./src/Content.sln"
  API_PROJECT_PATH: "./src/Content.API/Content.API.csproj"
  PUBLISH_DIR: "./publish"
  ARTIFACTS_DIR: "./src/Content.API/publish" # Artifacts will be picked from this directory
  DB_CONTEXT_NAME: "ContentDbContext"  

on:
  workflow_dispatch:

permissions:
  id-token: write #For azure/login action to use OIDC
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login with OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Set up dependency caching for faster builds
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: .NET Build
        run: dotnet build ${{ env.SOLUTION_PATH }} --configuration Release
        
      - name: Test
        run: dotnet test ${{ env.SOLUTION_PATH }} --filter Category!=Ignore --configuration Release --no-restore --no-build --verbosity normal
        env:
          ConnectionStrings__DefaultConnection: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          DatabaseProvider: "Production"
        
      - name: Publish Artifacts
        run: dotnet publish ${{ env.API_PROJECT_PATH }} --configuration Release --no-restore --no-build --property:PublishDir=${{ env.PUBLISH_DIR }}

      - name: Install EF Core CLI tool
        run: dotnet tool install --global dotnet-ef

      - name: Apply Entity Framework Migrations
        run: dotnet ef database update --project Content.Infrastructure/Content.Infrastructure.csproj --startup-project Content.API/Content.API.csproj --context ${{ env.DB_CONTEXT_NAME }}
        working-directory: ./src/
        env:
          ConnectionStrings__DefaultConnection: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          DatabaseProvider: "Production"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ env.ARTIFACTS_DIR }}

  deploy:
    name: Deploy as Azure App
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Deploy
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
