# This workflow will build and test a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI for .NET Web APIs and React App

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
    paths-ignore:
    - '**.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
    - '**.md'
    
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Restore .NET dependencies
      run: dotnet restore src/Wisgenix.sln
      
    - name: Build .NET Solution
      run: dotnet build src/Wisgenix.sln --configuration Release --no-restore
      
    - name: Run .NET Tests
      run: dotnet test src/Wisgenix.sln --configuration Release --no-build --verbosity normal --logger trx --results-directory ./test-results
      
    - name: Upload .NET Test Results
      uses: actions/upload-artifact@v4
      if: always() # Upload even if tests fail
      with:
        name: dotnet-test-results
        path: ./test-results/dotnet

    # ----------------------------------------
    # Next.js (React) App Build
    # ----------------------------------------
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x' # Specify your Node.js version
        cache: 'npm'         # Caches npm dependencies to speed up builds
        cache-dependency-path: 'src/Wisgenix.Web/package-lock.json' # Adjust if you use yarn.lock or pnpm-lock.yaml

    - name: Install React dependencies
      run: npm install
      working-directory: src/Wisgenix.Web

    - name: Build React App
      run: npm run build
      working-directory: src/Wisgenix.Web

    - name: Upload React Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nextjs-build-output
        path: src/Wisgenix.Web/.next # Or whatever your Next.js build output directory is (commonly .next or build)
